## These properties are only applied for embedded tomcat
server.port=9001
debug=true

## Datasource Properties
spring.datasource.url=jdbc:h2:mem:mydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

## JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.validator.apply_to_ddl=false
#spring.jpa.properties.hibernate.check_nullability=true

## H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

## enabling the DEBUG level for Request logging filter
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

## Authentication and Authorization
auth.api.username=admin
auth.api.password=2020
auth.api.organization=thales
auth.jwt.sign.key=d2VsY29tZQ==
auth.jwt.lifetime=2
